// Page copy for the ATM store (PRODUCT-DESCRIPTIONS.md). Prices never appear
// here as numbers: `{from}` renders this model's lowest price and
// `{from:<sku>}` another model's, both computed from lib/catalog.js.
// `[text](sku:<sku>)` links to a model page; `[text](page:<file>)` links to a
// page in /pages/.

export const TRUST_STRIP = [
  { icon: '🛟', label: 'Free 24/7 Support' },
  { icon: '⚙️', label: 'Free Transaction Processing Setup' },
  { icon: '🧾', label: 'No Hidden Fees' },
  { icon: '📋', label: 'Free Programming Sheet' },
];

// Shown under every trust strip so the processing badge isn't read as unconditional.
export const TRUST_NOTE = 'Processing setup is free when you process with Ford Frontier Investments. An outside processor adds a $500 setup fee.';

export const PRODUCT_CONTENT = {
  'halo-ii': {
    seoTitle: 'Buy Hyosung Halo II ATM Machine | Best-Selling Retail ATM | Ford Frontier Investments',
    metaDescription: "Own the industry's best-selling retail ATM. Hyosung Halo II — starting at {from}, free shipping in the continental US, 2-year manufacturer warranty. Configure and buy online.",
    badge: "Industry's #1 ATM",
    cardTagline: 'The best-selling retail ATM in the industry. Best value with proven reliability and enhanced security features.',
    bestFor: 'First-time ATM owners, bars, convenience stores, barbershops — anywhere that wants proven reliability without paying for features it won\'t use.',
    h1: 'Own the Best-Selling Retail ATM in America',
    hook: "The Hyosung Halo II isn't the flashiest machine on this page — it's the one that just works, which is exactly why it's the best-selling retail ATM in the industry. If you're buying your first machine, or your fifth, the Halo II is the safe, proven choice.",
    features: [
      '10.1" high-resolution color display',
      'EMV chip reader standard; NFC contactless reader available as a factory add-on',
      'UL 291 business-hours safe with added break-in protection',
      'PCI 3.0 compliant keypad, TLS-encrypted communications',
      'Cassette options from 1,000 notes up to dual 2,000-note capacity',
      'ADA compliant',
    ],
    why: "If you're weighing this against the [Force](sku:force) or the [2800T](sku:2800t), the difference is simple: the Force steps up in screen size and presence, and the 2800T steps up in cash capacity and adds a through-the-wall install, both at a higher price. The Halo II is the right call when reliability and value matter more than square footage of screen.",
    compare: ['force', '2800t', 'g2500'],
    faq: [
      ['How much does a Hyosung Halo II ATM cost?', 'Pricing starts at {from} for the 1,000-note cassette configuration and increases with cassette size and any add-ons selected (lock, keypad, topper, NFC reader, programming, or processing setup).'],
      ['Does the Halo II support tap-to-pay (NFC)?', "NFC is available as an add-on, not standard. Adding it at the time of purchase is cheaper than retrofitting it later, since it's installed at the factory."],
      ["What's the warranty on a new Halo II?", 'New units carry a 2-year manufacturer warranty; used/refurbished units carry a 90-day warranty.'],
      ['Is the Halo II a good fit for a small business with its first ATM?', "Yes — it's the industry's best-selling retail ATM specifically because it balances upfront cost, reliability, and ease of service, which makes it the standard recommendation for a first machine."],
    ],
  },
  force: {
    seoTitle: 'Buy Hyosung Force ATM Machine | Large-Display Retail ATM | Ford Frontier Investments',
    metaDescription: 'The Hyosung Force steps up with a 12.1" touch display and an integrated topper. Up to 4,000-note capacity. Starting at {from}. Free shipping in the continental US.',
    badge: 'Bigger Screen',
    cardTagline: 'Upgraded from the Halo II with a larger display, integrated topper, and through-the-wall capability.',
    bestFor: 'High-traffic bars, nightclubs, and event venues that want a bigger screen, a brighter topper, and faster service calls than a standard machine offers.',
    h1: 'Built for the Locations That Never Slow Down',
    hook: 'When a location sees heavy use, the Force is built for it: a bigger 12.1" touch screen, an integrated topper that stands out in any lighting, and service features built for the machines that actually get used hard.',
    features: [
      '12.1" capacitive touch display with function keys',
      'Integrated topper with three-level brightness control, for visibility in any lighting',
      'Available as through-the-wall or freestanding',
      'Up to 4,000-note cash capacity with dual 2,000-note cassettes',
      'Vault light and wireless mounting bracket, built for faster, easier service calls',
      'Optional security camera add-on',
    ],
    why: 'If you want a bigger screen for advertising or faster servicing than the [Halo II](sku:halo-ii) offers, the Force is the upgrade — same reliability, more presence. If you need more than 4,000 notes of cash capacity, or a dedicated through-the-wall install, look at the [2800T](sku:2800t), which holds up to 6,000 notes.',
    compare: ['halo-ii', '2800t', 'onyx'],
    faq: [
      ['How much does a Hyosung Force ATM cost?', 'Pricing starts at {from} for the 1,000-note cassette configuration and scales up with cassette size and any add-ons.'],
      ['How much cash does the Force hold?', "Up to 4,000 notes with the Dual 2K cassette configuration. That's the same top capacity as the Halo II; if you need more, the 2800T holds up to 6,000 notes."],
      ['Can the Force be installed through-the-wall?', 'Yes, the Force supports both through-the-wall and freestanding installation.'],
      ['Does the Force include a security camera?', 'Not standard — a security camera is available as an add-on for locations that want in-machine transaction monitoring.'],
    ],
  },
  '2800t': {
    seoTitle: 'Buy Hyosung 2800T ATM Machine | Through-the-Wall ATM | Ford Frontier Investments',
    metaDescription: 'The Hyosung 2800T is a weatherized through-the-wall ATM built for high-demand locations. Up to 6,000-note capacity. Starting at {from}. Free shipping in the continental US.',
    badge: 'Through-the-Wall',
    cardTagline: 'A weatherized through-the-wall ATM for gas stations, drive-ups, and permanent installs.',
    bestFor: 'Locations that need a permanent through-the-wall install — gas stations, drive-up locations, and high-end retail that wants the walk-up ATM experience.',
    h1: 'A Through-the-Wall ATM Built to Stay Out in the Weather',
    hook: 'The 2800T is the machine for a location that wants an ATM built into the wall, not sitting on the floor — weatherized, high-capacity, and designed for the kind of service ease that keeps a fixed installation running for years.',
    features: [
      '12.1" display with capacitive touch function keys',
      'Supports up to three removable cassettes — up to 6,000-note total capacity',
      'Weatherized, water-resistant exterior for outdoor and drive-up installs',
      'Illuminated topper and vault service light for easier loading and maintenance',
      'Braille keypad, digital receipts, and support for six languages',
      'UL291 business-hours safe, with a Level 1 safe upgrade available',
    ],
    why: "This is the through-the-wall option on this page. If your location has floor space and doesn't need a permanent wall install, the [Force](sku:force) gives you a similar large display at a lower price point, though it tops out at 4,000 notes. Choose the 2800T specifically when the installation itself needs to be through-the-wall.",
    compare: ['force', 'gt300', 'gt500'],
    faq: [
      ['How much does a Hyosung 2800T ATM cost?', 'Pricing starts at {from} for the 2,000-note cassette configuration and increases with cassette size and add-ons.'],
      ['Is the 2800T weatherproof?', 'Yes — the 2800T has a weatherized, water-resistant exterior designed for outdoor and drive-up through-the-wall installations.'],
      ['How much cash can the 2800T hold?', 'Up to three 2,000-note cassettes, for a total capacity of up to 6,000 notes.'],
      ['What languages does the 2800T support?', 'English, Spanish, French, Japanese, Chinese, and Korean.'],
    ],
  },
  g2500: {
    seoTitle: 'Buy Genmega G2500 ATM Machine | Best Value Retail ATM | Ford Frontier Investments',
    metaDescription: "Genmega's flagship base model — compact, reliable, and the best entry price on this page. Starting at {from}. Free shipping in the continental US. Configure and buy online.",
    badge: 'Best Value',
    cardTagline: "Genmega's flagship base model — reliable, compact, and packed with features for any retail environment.",
    bestFor: 'Tight spaces — small retail counters, barbershops, and convenience stores that need a compact footprint without giving up features.',
    h1: "Genmega's Flagship, Built for Tight Spaces",
    hook: "The G2500 is Genmega's best-value model and the lowest price of entry on this page — a compact footprint that still gives you an upgrade path if your needs grow.",
    features: [
      '8" wide color LCD, upgradeable to a 10.2" touchscreen',
      '2" receipt printer, upgradeable to 3" for graphics-capable receipts and coupons',
      'Integrated topper, with LED topper upgrades available',
      'Compact footprint designed for tight retail spaces',
      'Supports third-party cash dispensers for flexible upgrades',
      'NFC contactless reader available as a factory add-on',
    ],
    why: 'If price and footprint are the deciding factors, this is the pick. Want a more modern-looking cabinet at a similar footprint? Compare it to the [Onyx](sku:onyx). Want something with more visual presence for a high-traffic spot? Look at the [Nova](sku:nova) instead.',
    compare: ['onyx', 'nova', 'halo-ii'],
    faq: [
      ['How much does a Genmega G2500 ATM cost?', 'Pricing starts at {from} for the 1,000-note cassette configuration and increases with cassette size and add-ons like the touchscreen LCD or NFC reader.'],
      ['Can the screen be upgraded?', 'Yes — the standard 8" LCD can be upgraded to a 10.2" touchscreen.'],
      ['Does the G2500 support tap-to-pay (NFC)?', "NFC is available as an add-on, not standard. Adding it at purchase is cheaper than retrofitting it later, since it's installed at the factory."],
      ['Is the G2500 a good fit for a small retail counter?', "Yes — its compact footprint is specifically designed for tight spaces where a full-size ATM cabinet wouldn't fit."],
    ],
  },
  onyx: {
    seoTitle: 'Buy Genmega Onyx ATM Machine | Modern Design ATM | Ford Frontier Investments',
    metaDescription: 'A modern upgrade from the G2500 with a reflective security front and touch function keys. Starting at {from}. Free shipping in the continental US. Configure and buy online.',
    badge: 'Most Popular Genmega',
    cardTagline: 'A modern upgrade from the G2500 with a larger display, touch function keys, and attention-commanding design.',
    bestFor: 'Hotels, clubs, and gas stations that want an ATM that looks the part — a higher-end cabinet design that reassures customers before they even use it.',
    h1: 'A Modern Design That Puts Customers at Ease',
    hook: 'The Onyx looks like a high-end financial ATM, not a retrofit — a reflective front bezel and touch function keys that make it a natural fit anywhere first impressions matter, from hotel lobbies to upscale retail.',
    features: [
      '10.1" color LCD, upgradeable to a 12" touchscreen',
      'Reflective front bezel for a premium look and added transaction privacy',
      'Touch function keys for a more modern user experience',
      'Optional 3" printer for receipt graphics and branding',
      'Integrated topper, with LED topper upgrades available',
      'NFC contactless reader available as a factory add-on',
    ],
    why: "Choose the Onyx over the [G2500](sku:g2500) when the machine's appearance matters to your customers — hotels, clubs, and upscale retail are the classic fit. If footprint and price matter more than styling, the G2500 covers the same core specs for less.",
    compare: ['g2500', 'nova', 'onyx-w'],
    faq: [
      ['How much does a Genmega Onyx ATM cost?', 'Pricing starts at {from} for the 1,000-note cassette configuration and increases with cassette size and add-ons.'],
      ['What makes the Onyx different from the G2500?', 'The Onyx has a more modern cabinet design with a reflective front bezel and touch function keys, plus a larger standard screen and touchscreen upgrade option.'],
      ['Does the Onyx support tap-to-pay (NFC)?', 'NFC is available as an add-on, not standard. Adding it at purchase is cheaper than retrofitting it later.'],
      ['Is the Onyx a good fit for a hotel or club?', 'Yes — its design is specifically built to look and feel like a premium financial ATM, which locations like hotels and clubs often prefer for guest-facing placements.'],
    ],
  },
  'onyx-w': {
    seoTitle: 'Buy Genmega Onyx W ATM Machine | Wall-Mount ATM | Ford Frontier Investments',
    metaDescription: 'Wall-mount or countertop ATM for space-limited locations. Starting at {from}. Free shipping in the continental US. Configure and buy online.',
    badge: 'Wall-Mount',
    cardTagline: 'Wall-mount or countertop version of the Onyx — perfect for space-restricted locations.',
    bestFor: "Locations with no floor space to spare — small retail counters, tight hallways, or anywhere a standard freestanding cabinet won't fit.",
    h1: "When There's No Floor Space to Spare",
    hook: "The Onyx W solves one specific problem: not enough floor space for a standard ATM. Wall-mounted or countertop, it fits where a freestanding cabinet can't.",
    features: [
      'Installs as wall-mount or countertop',
      '10.1" LED screen with light-up touch function keys',
      '1,000 or 2,000-note cassette options',
      'Compact design built specifically for space-limited locations',
      'NFC contactless reader available as a factory add-on',
    ],
    why: 'This is the space-constrained answer, not a general-purpose pick. If you have normal floor space available, the [G2500](sku:g2500) or [Onyx](sku:onyx) give you more configuration options for a similar price.',
    compare: ['onyx', 'g2500', 'gt300'],
    faq: [
      ['How much does a Genmega Onyx W ATM cost?', 'Pricing starts at {from} for the 1,000-note cassette configuration.'],
      ['Can the Onyx W be mounted on a wall?', "Yes — it's designed to install as either a wall-mount or a countertop unit, unlike Genmega's freestanding models."],
      ['Does the Onyx W support tap-to-pay (NFC)?', 'NFC is available as an add-on, not standard. Adding it at purchase is cheaper than retrofitting it later.'],
      ['What locations is the Onyx W built for?', "Locations where floor space is limited — small counters, tight hallways, or retrofits where a freestanding cabinet isn't an option."],
    ],
  },
  nova: {
    seoTitle: 'Buy Genmega Nova ATM Machine | Digital Display ATM | Ford Frontier Investments',
    metaDescription: "Genmega's newest ATM — a 17\" touchscreen with full-motion video built in, no separate digital topper needed. Starting at {from}. Free shipping in the continental US.",
    badge: 'Newest Model',
    cardTagline: "Genmega's newest retail ATM. Attention-grabbing lights, large screen, and next-generation features.",
    bestFor: 'High-traffic locations that want a machine that doubles as an attention-grabbing digital sign — bars, event venues, and busy retail.',
    h1: 'The ATM That Doubles as Your Digital Sign',
    hook: "The Nova runs full-motion video on the top half of a 17\" touchscreen while handling transactions on the bottom — a built-in digital topper, without paying for a separate one. It's the machine built to get noticed.",
    features: [
      '17" vertical capacitive touchscreen with full-motion video support',
      'LED edge lighting around the cash dispenser and keypad for a standout look',
      'Built on the same proven, field-tested vault and security components as the G2500 and Onyx',
      'No separate digital topper required — video runs on the main screen',
      'NFC contactless reader available as a factory add-on',
    ],
    why: "Pick the Nova when visibility and customer engagement matter as much as the transaction itself — it's the most attention-grabbing machine on this page, at a price between the [G2500](sku:g2500)/[Onyx](sku:onyx) and the higher-capacity through-the-wall models.",
    compare: ['onyx', 'g2500', 'force'],
    faq: [
      ['How much does a Genmega Nova ATM cost?', 'Pricing starts at {from} for the 1,000-note cassette configuration and increases with cassette size and add-ons.'],
      ['Does the Nova need a separate digital topper?', 'No — its 17" touchscreen displays full-motion video directly, which replaces the need for a separate digital topper.'],
      ['Is the Nova built on new or proven components?', "The Nova uses the same field-tested vault and security components as the G2500 and Onyx, so reliability isn't a trade-off for the newer screen technology."],
      ['Does the Nova support tap-to-pay (NFC)?', 'NFC is available as an add-on, not standard. Adding it at purchase is cheaper than retrofitting it later.'],
    ],
  },
  gt300: {
    seoTitle: 'Buy Genmega GT300 ATM Machine | Compact Through-the-Wall ATM | Ford Frontier Investments',
    metaDescription: 'A compact, weather-resistant through-the-wall ATM for tight spaces. Starting at {from}. Free shipping in the continental US. Configure and buy online.',
    badge: 'Compact TTW',
    cardTagline: 'A compact, weather-resistant through-the-wall ATM for kiosks and small storefronts.',
    bestFor: "Kiosks, small storefronts, and outdoor locations that want a through-the-wall install but don't have room for a full-size unit.",
    h1: 'Through-the-Wall, Without the Footprint',
    hook: "Most through-the-wall ATMs need real space behind the wall. The GT300 doesn't — a compact, weather-resistant chassis that brings walk-up convenience to locations that couldn't fit a standard through-the-wall machine.",
    features: [
      '7" high-resolution color LCD with customizable ad screens',
      'Weather-resistant enclosure, built for outdoor installation',
      '2,000-note rear-load removable cassette',
      'Optional rear service panel for secure, convenient loading',
      'Compact chassis purpose-built for kiosks and tight indoor or outdoor spots',
    ],
    why: 'This is the right through-the-wall pick specifically when space is the constraint. For a higher-capacity through-the-wall install with more cash headroom, the [GT500](sku:gt500) is the step up.',
    compare: ['gt500', '2800t', 'onyx-w'],
    faq: [
      ['How much does a Genmega GT300 ATM cost?', 'Pricing starts at {from} for the 2,000-note cassette configuration and increases with add-ons.'],
      ['Is the GT300 weather-resistant?', "Yes — it's built with a weather-resistant enclosure specifically for outdoor through-the-wall installations."],
      ['How much cash does the GT300 hold?', 'The GT300 we sell comes with a 2,000-note rear-load removable cassette.'],
      ['What locations is the GT300 built for?', 'Compact, space-constrained locations that still want a through-the-wall install — kiosks, small storefronts, and tight outdoor spots.'],
    ],
  },
  gt500: {
    seoTitle: 'Buy Genmega GT500 ATM Machine | High-Capacity Through-the-Wall ATM | Ford Frontier Investments',
    metaDescription: 'A premium through-the-wall ATM with a 15" display and up to 3-cassette capacity. Starting at {from}. Free shipping in the continental US. Configure and buy online.',
    badge: 'Premium TTW',
    cardTagline: 'A high-capacity through-the-wall ATM with a 15" advertising display and up to three cassettes.',
    bestFor: 'High-volume through-the-wall installations that need bank-level capacity and presentation — high-traffic retail, large venues, and multi-location operators.',
    h1: 'Bank-Level Capacity, Built for the Wall',
    hook: 'The GT500 is the high-capacity answer for a through-the-wall install — a 15" high-bright display for advertising, up to three cassettes of cash capacity, and a touchscreen rear service panel that makes servicing it fast even at high transaction volume.',
    features: [
      '15" high-bright color LCD, built to support custom advertising',
      'Up to three 2,000-note cassettes with a motorized bill presenter',
      '7" touchscreen rear service panel for secure, convenient cash loading',
      'ADA and PCI compliant, EMV-ready',
      'Built for locations where transaction volume and uptime both matter',
    ],
    why: "This is the top of the through-the-wall lineup on this page — choose it when the [GT300](sku:gt300)'s capacity isn't enough for your volume. For a lower-capacity, lower-cost through-the-wall option, the GT300 covers smaller locations.",
    compare: ['gt300', '2800t', 'force'],
    faq: [
      ['How much does a Genmega GT500 ATM cost?', 'Pricing starts at {from} for the 2,000-note cassette configuration and increases with cassette size.'],
      ['How much cash can the GT500 hold?', 'Up to three 2,000-note cassettes with a motorized bill presenter, for high-volume cash handling.'],
      ['What makes the GT500 different from the GT300?', "The GT500 is built for significantly higher transaction volume — a larger 15\" advertising display, up to three cassettes of capacity, and a touchscreen rear service panel, versus the GT300's compact, space-saving design."],
      ['Is the GT500 a good fit for a high-traffic location?', "Yes — it's built specifically for locations where cash capacity and servicing speed matter more than footprint."],
    ],
  },
};

// Shared FAQ items added to every product page after the model-specific ones.
export const SHARED_PRODUCT_FAQ = [
  ['Is processing setup free?', "Yes, when you process with Ford Frontier Investments — setup is free and covers all major networks. If you'd rather use a different processor, a $500 outside-processor setup fee applies. You choose this under Processing Setup when you configure your machine."],
  ['How does the machine get programmed?', 'Your choice: program it yourself for free using the included programming sheet, with phone help from Ford Frontier Investments during business hours; add factory programming for $150 per machine so it arrives ready to use; or add an on-site technician for $250 to program it in person.'],
  ['Is shipping free?', 'Yes — every machine ships free within the continental United States. Machines are ordered from the distributor after purchase and typically ship within about 2 weeks.'],
  ['Do you offer bulk pricing?', 'Orders of 10 or more machines, in any mix of models, may qualify for bulk pricing. Call (205) 210-8121 before checking out.'],
];
