// Builds the ATM store pages from lib/catalog.js (prices) and the content
// modules (copy). Run after changing either:
//
//   npm run build           write the generated files
//   npm run build -- --check fail if any generated file is out of date
//
// Generated: assets/data/catalog.json, pages/atm/*.html (one per model),
// the five guide pages, and the trust strip, model cards and ItemList schema
// on buy-atm.html.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ATM_CATALOG, BULK_PRICING_THRESHOLD, fromPrice, productName, publicCatalog } from '../lib/catalog.js';
import { PRODUCT_CONTENT, SHARED_PRODUCT_FAQ, TRUST_NOTE, TRUST_STRIP } from '../lib/store-content.js';
import { PILLAR_PAGES } from '../lib/pillar-content.js';

const SITE = 'https://fordfrontierinvestments.com';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', 'files', 'ffi-website');
// Non-breaking space and hyphen so the number never wraps mid-way.
const PHONE_DISPLAY = '(205)&nbsp;210&#8209;8121';
const PHONE_TEL = 'tel:+12052108121';
const CHECK = process.argv.includes('--check');

// ── Formatting helpers ──────────────────────────────────────────────────────

export function money(cents) {
  const dollars = cents / 100;
  return '$' + dollars.toLocaleString('en-US', {
    minimumFractionDigits: Number.isInteger(dollars) ? 0 : 2,
    maximumFractionDigits: 2,
  });
}

function esc(text) {
  return String(text)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// `depth` is how deep the page sits: 1 for /pages/x.html, 2 for /pages/atm/x.html.
function hrefFor(target, depth) {
  const [kind, value] = target.split(':');
  if (kind === 'sku') {
    const page = ATM_CATALOG[value]?.page;
    if (!page) throw new Error(`Unknown sku link: ${value}`);
    return depth === 2 ? page : `atm/${page}`;
  }
  if (kind === 'page') return depth === 2 ? `../${value}` : value;
  if (kind === 'root') return depth === 2 ? `../../${value}` : `../${value}`;
  throw new Error(`Unknown link target: ${target}`);
}

function fillPrices(text, sku) {
  return text.replace(/\{from(?::([a-z0-9-]+))?\}/g, (_, other) => {
    const key = other || sku;
    if (!ATM_CATALOG[key]) throw new Error(`Unknown sku in price token: ${key}`);
    return money(fromPrice(key));
  });
}

// Escaped HTML with [text](sku:x|page:x|root:x) links and **bold**.
function rich(text, depth, sku) {
  return esc(fillPrices(text, sku))
    .replace(/\[([^\]]+)\]\(((?:sku|page|root):[^)]+)\)/g, (_, label, target) => `<a href="${hrefFor(target, depth)}">${label}</a>`)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
}

// Plain text for JSON-LD: links become their label.
function plain(text, sku) {
  return fillPrices(text, sku).replace(/\[([^\]]+)\]\([^)]+\)/g, '$1').replace(/\*\*([^*]+)\*\*/g, '$1');
}

function jsonLd(obj) {
  // Escape "<" so no string in the data can close the script element.
  return `<script type="application/ld+json">\n${JSON.stringify(obj, null, 2).replace(/</g, '\\u003c')}\n</script>`;
}

function faqSchema(faq, sku) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faq.map(([q, a]) => ({
      '@type': 'Question',
      name: plain(q, sku),
      acceptedAnswer: { '@type': 'Answer', text: plain(a, sku) },
    })),
  };
}

// ── Shared page chrome ──────────────────────────────────────────────────────

function pageShell({ depth, title, description, canonicalPath, schemas = [], body, noindex = false }) {
  const up = depth === 2 ? '../../' : '../';
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}" />
${noindex ? '  <meta name="robots" content="noindex" />\n' : ''}  <link rel="canonical" href="${SITE}/${canonicalPath}" />
${schemas.map((s) => jsonLd(s).replace(/^/gm, '  ')).join('\n')}
  <link rel="stylesheet" href="${up}assets/css/main.css" />
  <link rel="stylesheet" href="${up}assets/css/mobile-fix.css" />
</head>
<body class="store-page">
<!-- Generated by scripts/build-store.mjs from lib/. Edit those, not this file. -->
<div id="site-nav"></div>
${body}
<div id="site-footer"></div>
<script src="${up}assets/js/layout.js"></script>
<script src="${up}assets/js/main.js"></script>
</body>
</html>
`;
}

function hero({ depth, crumbs, eyebrow, h1, sub }) {
  const trail = crumbs
    .map(([label, target]) => (target ? `<a href="${hrefFor(target, depth)}">${esc(label)}</a>` : `<span aria-current="page">${esc(label)}</span>`))
    .join(' <span aria-hidden="true">/</span> ');
  return `<section class="page-hero">
  <div class="container">
    <nav class="store-breadcrumb" aria-label="Breadcrumb">${trail}</nav>
    ${eyebrow ? `<p class="store-eyebrow">${esc(eyebrow)}</p>` : ''}
    <h1>${esc(h1)}</h1>
    ${sub ? `<p class="store-hero-sub">${sub}</p>` : ''}
  </div>
</section>`;
}

function trustStrip() {
  return `<ul class="trust-strip">
${TRUST_STRIP.map((t) => `  <li class="trust-strip__item"><span class="trust-strip__icon" aria-hidden="true">${t.icon}</span>${esc(t.label)}</li>`).join('\n')}
</ul>
<p class="trust-note">${esc(TRUST_NOTE)}</p>`;
}

function photo(sku, { loading = 'eager' } = {}) {
  const p = ATM_CATALOG[sku];
  const name = productName(sku);
  const placeholder = `<div class="photo-placeholder" role="img" aria-label="${esc(name)} photo coming soon"><span class="photo-placeholder__name">${esc(name)}</span><span class="photo-placeholder__note">Photo coming soon</span></div>`;
  if (!p.image) return placeholder;
  // store.js swaps in the placeholder if the manufacturer's image fails to load.
  return `<img src="${esc(p.image)}" alt="${esc(name)} ATM machine" loading="${loading}" data-fallback-label="${esc(name)}" />`;
}

function faqSection(faq, { depth, sku, idPrefix }) {
  return `<div class="faq-list">
${faq.map(([q, a], i) => `  <div class="faq-item">
    <h3 class="faq-item__heading"><button type="button" class="faq-item__q" id="${idPrefix}-q${i + 1}" aria-expanded="false" aria-controls="${idPrefix}-a${i + 1}">${rich(q, depth, sku)}</button></h3>
    <div class="faq-item__a" id="${idPrefix}-a${i + 1}"><p>${rich(a, depth, sku)}</p></div>
  </div>`).join('\n')}
</div>`;
}

function ctaBand(depth, heading, text) {
  return `<section class="store-cta">
  <div class="container">
    <h2>${esc(heading)}</h2>
    <p>${esc(text)}</p>
    <div class="store-cta__buttons">
      <a href="${PHONE_TEL}" class="btn btn--primary">${PHONE_DISPLAY}</a>
      <a href="${hrefFor('page:buy-atm.html', depth)}" class="btn btn--secondary">Browse All ATMs</a>
    </div>
  </div>
</section>`;
}

// ── Product pages ───────────────────────────────────────────────────────────

function optionText(choice) {
  return choice.amount ? `${choice.label} (+${money(choice.amount)})` : `${choice.label} (included)`;
}

function configurator(sku) {
  const p = ATM_CATALOG[sku];
  const cheapest = p.cassettes.reduce((a, b) => (b.amount < a.amount ? b : a));
  const cassettes = p.cassettes.map((c) => `        <label class="cassette-choice">
          <input type="radio" name="cassette" value="${c.key}"${c === cheapest ? ' checked' : ''} />
          <span class="cassette-choice__box"><span class="cassette-choice__name">${esc(c.label)}</span><span class="cassette-choice__price">${money(c.amount)}</span></span>
        </label>`).join('\n');

  const groups = p.optionGroups.map((g) => {
    const id = `opt-${g.key}`;
    const noteId = g.note ? `${id}-note` : null;
    return `      <div class="option-row">
        <label class="option-label" for="${id}">${esc(g.label)}</label>
        <select class="option-select" id="${id}" name="${g.key}"${noteId ? ` aria-describedby="${noteId}"` : ''}>
${g.choices.map((c, i) => `          <option value="${c.key}"${i === 0 ? ' selected' : ''}>${esc(optionText(c))}</option>`).join('\n')}
        </select>
${g.note ? `        <p class="option-note" id="${noteId}">${esc(g.note)}</p>\n` : ''}      </div>`;
  }).join('\n');

  return `<form class="configurator" data-configurator="${sku}" novalidate>
      <p class="configurator__brand">${esc(p.brand)} · ${esc(p.model)}</p>
      <h2 class="configurator__title">Configure Your ATM</h2>
      <fieldset class="option-row option-row--cassette">
        <legend class="option-label">Cassette</legend>
        <div class="cassette-choices">
${cassettes}
        </div>
      </fieldset>
${groups}
      <div class="buy-box__price">
        <span class="buy-box__price-label">Your price</span>
        <output class="buy-box__price-value" data-config-price aria-live="polite">${money(cheapest.amount)}</output>
        <p class="buy-box__price-meta">Free shipping in the continental US · Ships in about 2 weeks</p>
      </div>
      <button type="submit" class="btn btn--primary btn--lg buy-box__add">Add to Cart</button>
      <p class="buy-box__status" data-config-status role="status"></p>
      <p class="bulk-note">Buying ${BULK_PRICING_THRESHOLD}+ machines? Orders of ${BULK_PRICING_THRESHOLD} or more may qualify for bulk pricing — call <a href="${PHONE_TEL}">${PHONE_DISPLAY}</a>.</p>
    </form>`;
}

function productSchema(sku) {
  const p = ATM_CATALOG[sku];
  const c = PRODUCT_CONTENT[sku];
  const url = `${SITE}/pages/atm/${p.page}`;
  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: `${productName(sku)} ATM`,
    brand: { '@type': 'Brand', name: p.brand },
    ...(p.image && { image: p.image }),
    description: plain(c.metaDescription, sku),
    sku: `ffi-${sku}`,
    url,
    offers: {
      '@type': 'Offer',
      url,
      price: (fromPrice(sku) / 100).toFixed(2),
      priceCurrency: 'USD',
      availability: 'https://schema.org/InStock',
      itemCondition: 'https://schema.org/NewCondition',
      seller: { '@type': 'Organization', name: 'Ford Frontier Investments' },
      shippingDetails: {
        '@type': 'OfferShippingDetails',
        shippingRate: { '@type': 'MonetaryAmount', value: '0', currency: 'USD' },
        shippingDestination: { '@type': 'DefinedRegion', addressCountry: 'US' },
      },
    },
  };
}

function productPage(sku) {
  const p = ATM_CATALOG[sku];
  const c = PRODUCT_CONTENT[sku];
  const name = productName(sku);
  const depth = 2;
  const faq = [...c.faq, ...SHARED_PRODUCT_FAQ];

  const body = `${hero({
    depth,
    crumbs: [['Home', 'root:index.html'], ['Buy an ATM', 'page:buy-atm.html'], [name, null]],
    eyebrow: name,
    h1: c.h1,
    sub: `<strong>Best for:</strong> ${esc(c.bestFor)}`,
  })}

<section class="section product-section">
  <div class="container">
    <div class="product-layout">
      <figure class="product-photo">
        <span class="product-photo__badge">${esc(c.badge)}</span>
        ${photo(sku)}
      </figure>

      <aside class="buy-box" aria-label="Configure and buy the ${esc(name)}">
    ${configurator(sku)}
        ${trustStrip().replace(/\n/g, '\n        ')}
      </aside>

      <div class="product-details">
        <p class="product-hook">${esc(c.hook)}</p>
        <h2 class="store-h2">Features</h2>
        <ul class="product-features">
${c.features.map((f) => `          <li>${esc(f)}</li>`).join('\n')}
        </ul>
        <h2 class="store-h2">Why the ${esc(p.model)}?</h2>
        <p>${rich(c.why, depth, sku)}</p>
      </div>
    </div>
  </div>
</section>

<section class="section section--gray">
  <div class="container container--narrow">
    <p class="label">Common Questions</p>
    <h2 class="store-h2">${esc(p.model)} FAQ</h2>
    ${faqSection(faq, { depth, sku, idPrefix: 'faq' })}
    <p class="store-more-links">More questions? See the <a href="../atm-buying-faq.html">ATM buying FAQ</a>.</p>
  </div>
</section>

<section class="section">
  <div class="container">
    <p class="label">Compare other models</p>
    <h2 class="store-h2">Not sure the ${esc(p.model)} is the one?</h2>
    <ul class="compare-chips">
${c.compare.map((other) => `      <li><a class="compare-chip" href="${ATM_CATALOG[other].page}"><span class="compare-chip__name">${esc(productName(other))}</span><span class="compare-chip__price">From ${money(fromPrice(other))}</span></a></li>`).join('\n')}
    </ul>
    <p class="store-more-links"><a href="../buy-atm.html">See all ATM models</a> · <a href="../hyosung-vs-genmega.html">Hyosung vs. Genmega</a> · <a href="../new-vs-used-atm.html">New vs. used ATMs</a> · <a href="../how-to-start-an-atm-business.html">How to start an ATM business</a></p>
  </div>
</section>

${ctaBand(depth, `Ready to Own a ${p.model}?`, 'Configure above and add to cart — or call us to order over the phone.')}`;

  return pageShell({
    depth,
    title: c.seoTitle,
    description: plain(c.metaDescription, sku),
    canonicalPath: `pages/atm/${p.page}`,
    schemas: [productSchema(sku), faqSchema(faq, sku)],
    body,
  });
}

// ── Guide (pillar) pages ────────────────────────────────────────────────────

function pillarBlock(block, depth) {
  if (block.type === 'table') {
    return `<div class="store-table-wrap"><table class="store-table">
  <thead><tr>${block.head.map((h) => `<th scope="col">${esc(h)}</th>`).join('')}</tr></thead>
  <tbody>
${block.rows.map((r) => `    <tr><th scope="row">${esc(r[0])}</th>${r.slice(1).map((cell) => `<td>${rich(cell, depth)}</td>`).join('')}</tr>`).join('\n')}
  </tbody>
</table></div>`;
  }
  if (block.type === 'models') {
    return `<ul class="compare-chips">
${Object.keys(ATM_CATALOG).map((sku) => `  <li><a class="compare-chip" href="${hrefFor(`sku:${sku}`, depth)}"><span class="compare-chip__name">${esc(productName(sku))}</span><span class="compare-chip__price">From ${money(fromPrice(sku))}</span></a></li>`).join('\n')}
</ul>`;
  }
  return `<p>${rich(block, depth)}</p>`;
}

function pillarPage(page) {
  const depth = 1;
  const faqSections = page.faqSections || (page.faq ? [{ heading: null, items: page.faq }] : []);
  const allFaq = faqSections.flatMap((s) => s.items);
  let faqCount = 0;

  const sections = (page.sections || []).map((s) => `<section class="store-guide__section">
  <h2 class="store-h2">${esc(s.heading)}</h2>
  ${s.blocks.map((b) => pillarBlock(b, depth)).join('\n  ')}
</section>`).join('\n');

  const faqHtml = faqSections.map((s) => {
    const prefix = `faq${++faqCount}`;
    return `${s.heading ? `<h3 class="store-h3">${esc(s.heading)}</h3>` : ''}
${faqSection(s.items, { depth, idPrefix: prefix })}`;
  }).join('\n');

  const body = `${hero({ depth, crumbs: [['Home', 'root:index.html'], ['Buy an ATM', 'page:buy-atm.html'], [page.crumb, null]], eyebrow: 'ATM Buyer\'s Guide', h1: page.h1, sub: null })}

<section class="section">
  <div class="container container--narrow store-guide">
    <p class="store-lead">${rich(page.intro, depth)}</p>
${sections}
${allFaq.length ? `<section class="store-guide__section" aria-labelledby="guide-faq">
  <h2 class="store-h2" id="guide-faq">${esc(page.faqHeading || 'Frequently Asked Questions')}</h2>
  ${faqHtml}
</section>` : ''}
    <section class="store-guide__section">
      <h2 class="store-h2">Related Pages</h2>
      <ul class="store-related">
${page.related.map(([label, target]) => `        <li><a href="${hrefFor(target, depth)}">${esc(label)}</a></li>`).join('\n')}
      </ul>
    </section>
  </div>
</section>

${ctaBand(depth, 'Questions Before You Buy?', 'Call us — we\'ll help you pick the right machine for your location.')}`;

  return pageShell({
    depth,
    title: page.seoTitle,
    description: page.metaDescription,
    canonicalPath: `pages/${page.file}`,
    schemas: allFaq.length ? [faqSchema(allFaq)] : [],
    body,
    noindex: page.noindex,
  });
}

// ── Hub page regions ────────────────────────────────────────────────────────

// Card ids double as anchors (index.html links to #halo2); ids start with a letter.
const LEGACY_CARD_IDS = { 'halo-ii': 'halo2', '2800t': 'hyosung-2800t' };

function hubCard(sku) {
  const p = ATM_CATALOG[sku];
  const c = PRODUCT_CONTENT[sku];
  const cheapest = p.cassettes.reduce((a, b) => (b.amount < a.amount ? b : a));
  return `      <article class="atm-card${sku === 'halo-ii' || sku === 'onyx' ? ' atm-card--featured' : ''}" id="${LEGACY_CARD_IDS[sku] || sku}">
        <div class="atm-card__badge">${esc(c.badge)}</div>
        <div class="atm-card__brand">${esc(p.brand)}</div>
        <h3 class="atm-card__name"><a href="atm/${p.page}">${esc(p.model)}</a></h3>
        <p class="atm-card__tagline">${esc(c.cardTagline)}</p>
        <div class="atm-card__img">${photo(sku, { loading: 'lazy' })}</div>
        <ul class="atm-card__specs">
${c.features.slice(0, 4).map((f) => `          <li>${esc(f)}</li>`).join('\n')}
          <li>Free shipping in the continental US</li>
        </ul>
        <p class="atm-card__price"><span>Starting at</span> ${money(fromPrice(sku))}</p>
        <div class="atm-card__buttons">
          <a href="atm/${p.page}" class="btn btn--primary">Configure &amp; Buy</a>
          <button type="button" class="btn btn--outline" data-quick-add="${sku}" aria-label="Quick add ${esc(productName(sku))} with ${esc(cheapest.label)} cassette and standard options">Quick Add (${esc(cheapest.label)})</button>
        </div>
      </article>`;
}

function hubSchema() {
  return jsonLd({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: 'ATM machines for sale',
    itemListElement: Object.keys(ATM_CATALOG).map((sku, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      url: `${SITE}/pages/atm/${ATM_CATALOG[sku].page}`,
      name: `${productName(sku)} ATM`,
    })),
  }).replace(/^/gm, '  ');
}

function replaceRegion(html, name, content, file) {
  const re = new RegExp(`(<!-- STORE:${name} -->)[\\s\\S]*?(\\s*<!-- /STORE:${name} -->)`);
  if (!re.test(html)) throw new Error(`${file} is missing the STORE:${name} region`);
  // A function replacement, so "$2,585" in the content isn't read as a backreference.
  return html.replace(re, (_, open, close) => `${open}\n${content}${close}`);
}

function hubPage(html) {
  const bySku = (brand) => Object.keys(ATM_CATALOG).filter((sku) => ATM_CATALOG[sku].brand === brand);
  html = replaceRegion(html, 'SCHEMA', hubSchema(), 'buy-atm.html');
  html = replaceRegion(html, 'TRUST', trustStrip(), 'buy-atm.html');
  html = replaceRegion(html, 'HYOSUNG', bySku('Hyosung').map(hubCard).join('\n'), 'buy-atm.html');
  html = replaceRegion(html, 'GENMEGA', bySku('Genmega').map(hubCard).join('\n'), 'buy-atm.html');
  return html;
}

// ── Main ────────────────────────────────────────────────────────────────────

function outputs() {
  const files = new Map();
  files.set('assets/data/catalog.json', JSON.stringify(publicCatalog(), null, 2) + '\n');
  for (const sku of Object.keys(ATM_CATALOG)) files.set(`pages/atm/${ATM_CATALOG[sku].page}`, productPage(sku));
  for (const page of PILLAR_PAGES) files.set(`pages/${page.file}`, pillarPage(page));
  const hub = 'pages/buy-atm.html';
  files.set(hub, hubPage(readFileSync(join(ROOT, hub), 'utf8')));
  const cartPage = 'pages/cart.html';
  files.set(cartPage, replaceRegion(readFileSync(join(ROOT, cartPage), 'utf8'), 'TRUST', trustStrip(), cartPage));
  return files;
}

const stale = [];
for (const [file, content] of outputs()) {
  const path = join(ROOT, file);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) continue;
  if (CHECK) {
    stale.push(file);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${relative(process.cwd(), path)}`);
  }
}
if (CHECK && stale.length) {
  console.error(`Out of date (run npm run build): ${stale.join(', ')}`);
  process.exit(1);
}
